//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace izindeturizm.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfSalturturlistesi", Namespace="http://tempuri.org/", ItemName="salturturlistesi")]
    [System.SerializableAttribute()]
    public class ArrayOfSalturturlistesi : System.Collections.Generic.List<izindeturizm.ServiceReference1.salturturlistesi> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="salturturlistesi", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class salturturlistesi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int turidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TurKategoriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TurAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TurProgramiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DahilHizmetlerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HaricHizmetlerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TurFiyatiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TurParaBirimiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TurAnasayfaResmiField;
        
        private System.Nullable<System.DateTime> turbaslangictarihiField;
        
        private System.Nullable<System.DateTime> turbitistarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TurGunGeceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YolculukTuruField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TurAltKategoriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BebekYas1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BebekYas2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CocukYas1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CocukYas2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BebekFiyatiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CocukFiyatiField;
        
        private System.Nullable<double> DolarField;
        
        private System.Nullable<double> EuroField;
        
        private bool SatisDurumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private izindeturizm.ServiceReference1.TurGelismisUcret[] turfiyatlariField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IslemDurumuField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int turid {
            get {
                return this.turidField;
            }
            set {
                if ((this.turidField.Equals(value) != true)) {
                    this.turidField = value;
                    this.RaisePropertyChanged("turid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TurKategori {
            get {
                return this.TurKategoriField;
            }
            set {
                if ((object.ReferenceEquals(this.TurKategoriField, value) != true)) {
                    this.TurKategoriField = value;
                    this.RaisePropertyChanged("TurKategori");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TurAdi {
            get {
                return this.TurAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.TurAdiField, value) != true)) {
                    this.TurAdiField = value;
                    this.RaisePropertyChanged("TurAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TurProgrami {
            get {
                return this.TurProgramiField;
            }
            set {
                if ((object.ReferenceEquals(this.TurProgramiField, value) != true)) {
                    this.TurProgramiField = value;
                    this.RaisePropertyChanged("TurProgrami");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string DahilHizmetler {
            get {
                return this.DahilHizmetlerField;
            }
            set {
                if ((object.ReferenceEquals(this.DahilHizmetlerField, value) != true)) {
                    this.DahilHizmetlerField = value;
                    this.RaisePropertyChanged("DahilHizmetler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string HaricHizmetler {
            get {
                return this.HaricHizmetlerField;
            }
            set {
                if ((object.ReferenceEquals(this.HaricHizmetlerField, value) != true)) {
                    this.HaricHizmetlerField = value;
                    this.RaisePropertyChanged("HaricHizmetler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string TurFiyati {
            get {
                return this.TurFiyatiField;
            }
            set {
                if ((object.ReferenceEquals(this.TurFiyatiField, value) != true)) {
                    this.TurFiyatiField = value;
                    this.RaisePropertyChanged("TurFiyati");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string TurParaBirimi {
            get {
                return this.TurParaBirimiField;
            }
            set {
                if ((object.ReferenceEquals(this.TurParaBirimiField, value) != true)) {
                    this.TurParaBirimiField = value;
                    this.RaisePropertyChanged("TurParaBirimi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string TurAnasayfaResmi {
            get {
                return this.TurAnasayfaResmiField;
            }
            set {
                if ((object.ReferenceEquals(this.TurAnasayfaResmiField, value) != true)) {
                    this.TurAnasayfaResmiField = value;
                    this.RaisePropertyChanged("TurAnasayfaResmi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.Nullable<System.DateTime> turbaslangictarihi {
            get {
                return this.turbaslangictarihiField;
            }
            set {
                if ((this.turbaslangictarihiField.Equals(value) != true)) {
                    this.turbaslangictarihiField = value;
                    this.RaisePropertyChanged("turbaslangictarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.Nullable<System.DateTime> turbitistarihi {
            get {
                return this.turbitistarihiField;
            }
            set {
                if ((this.turbitistarihiField.Equals(value) != true)) {
                    this.turbitistarihiField = value;
                    this.RaisePropertyChanged("turbitistarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string TurGunGece {
            get {
                return this.TurGunGeceField;
            }
            set {
                if ((object.ReferenceEquals(this.TurGunGeceField, value) != true)) {
                    this.TurGunGeceField = value;
                    this.RaisePropertyChanged("TurGunGece");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string YolculukTuru {
            get {
                return this.YolculukTuruField;
            }
            set {
                if ((object.ReferenceEquals(this.YolculukTuruField, value) != true)) {
                    this.YolculukTuruField = value;
                    this.RaisePropertyChanged("YolculukTuru");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string TurAltKategori {
            get {
                return this.TurAltKategoriField;
            }
            set {
                if ((object.ReferenceEquals(this.TurAltKategoriField, value) != true)) {
                    this.TurAltKategoriField = value;
                    this.RaisePropertyChanged("TurAltKategori");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string BebekYas1 {
            get {
                return this.BebekYas1Field;
            }
            set {
                if ((object.ReferenceEquals(this.BebekYas1Field, value) != true)) {
                    this.BebekYas1Field = value;
                    this.RaisePropertyChanged("BebekYas1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string BebekYas2 {
            get {
                return this.BebekYas2Field;
            }
            set {
                if ((object.ReferenceEquals(this.BebekYas2Field, value) != true)) {
                    this.BebekYas2Field = value;
                    this.RaisePropertyChanged("BebekYas2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string CocukYas1 {
            get {
                return this.CocukYas1Field;
            }
            set {
                if ((object.ReferenceEquals(this.CocukYas1Field, value) != true)) {
                    this.CocukYas1Field = value;
                    this.RaisePropertyChanged("CocukYas1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string CocukYas2 {
            get {
                return this.CocukYas2Field;
            }
            set {
                if ((object.ReferenceEquals(this.CocukYas2Field, value) != true)) {
                    this.CocukYas2Field = value;
                    this.RaisePropertyChanged("CocukYas2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string BebekFiyati {
            get {
                return this.BebekFiyatiField;
            }
            set {
                if ((object.ReferenceEquals(this.BebekFiyatiField, value) != true)) {
                    this.BebekFiyatiField = value;
                    this.RaisePropertyChanged("BebekFiyati");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string CocukFiyati {
            get {
                return this.CocukFiyatiField;
            }
            set {
                if ((object.ReferenceEquals(this.CocukFiyatiField, value) != true)) {
                    this.CocukFiyatiField = value;
                    this.RaisePropertyChanged("CocukFiyati");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=20)]
        public System.Nullable<double> Dolar {
            get {
                return this.DolarField;
            }
            set {
                if ((this.DolarField.Equals(value) != true)) {
                    this.DolarField = value;
                    this.RaisePropertyChanged("Dolar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=21)]
        public System.Nullable<double> Euro {
            get {
                return this.EuroField;
            }
            set {
                if ((this.EuroField.Equals(value) != true)) {
                    this.EuroField = value;
                    this.RaisePropertyChanged("Euro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=22)]
        public bool SatisDurum {
            get {
                return this.SatisDurumField;
            }
            set {
                if ((this.SatisDurumField.Equals(value) != true)) {
                    this.SatisDurumField = value;
                    this.RaisePropertyChanged("SatisDurum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public izindeturizm.ServiceReference1.TurGelismisUcret[] turfiyatlari {
            get {
                return this.turfiyatlariField;
            }
            set {
                if ((object.ReferenceEquals(this.turfiyatlariField, value) != true)) {
                    this.turfiyatlariField = value;
                    this.RaisePropertyChanged("turfiyatlari");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string IslemDurumu {
            get {
                return this.IslemDurumuField;
            }
            set {
                if ((object.ReferenceEquals(this.IslemDurumuField, value) != true)) {
                    this.IslemDurumuField = value;
                    this.RaisePropertyChanged("IslemDurumu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TurGelismisUcret", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TurGelismisUcret : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int TurUcretIDField;
        
        private System.Nullable<int> TurUcretSubIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UcretTipiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UcretField;
        
        private System.Nullable<System.DateTime> turbaslangictarihiField;
        
        private System.Nullable<System.DateTime> turbitistarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tarihtablosuField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TurUcretID {
            get {
                return this.TurUcretIDField;
            }
            set {
                if ((this.TurUcretIDField.Equals(value) != true)) {
                    this.TurUcretIDField = value;
                    this.RaisePropertyChanged("TurUcretID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> TurUcretSubID {
            get {
                return this.TurUcretSubIDField;
            }
            set {
                if ((this.TurUcretSubIDField.Equals(value) != true)) {
                    this.TurUcretSubIDField = value;
                    this.RaisePropertyChanged("TurUcretSubID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UcretTipi {
            get {
                return this.UcretTipiField;
            }
            set {
                if ((object.ReferenceEquals(this.UcretTipiField, value) != true)) {
                    this.UcretTipiField = value;
                    this.RaisePropertyChanged("UcretTipi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Ucret {
            get {
                return this.UcretField;
            }
            set {
                if ((object.ReferenceEquals(this.UcretField, value) != true)) {
                    this.UcretField = value;
                    this.RaisePropertyChanged("Ucret");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<System.DateTime> turbaslangictarihi {
            get {
                return this.turbaslangictarihiField;
            }
            set {
                if ((this.turbaslangictarihiField.Equals(value) != true)) {
                    this.turbaslangictarihiField = value;
                    this.RaisePropertyChanged("turbaslangictarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<System.DateTime> turbitistarihi {
            get {
                return this.turbitistarihiField;
            }
            set {
                if ((this.turbitistarihiField.Equals(value) != true)) {
                    this.turbitistarihiField = value;
                    this.RaisePropertyChanged("turbitistarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string tarihtablosu {
            get {
                return this.tarihtablosuField;
            }
            set {
                if ((object.ReferenceEquals(this.tarihtablosuField, value) != true)) {
                    this.tarihtablosuField = value;
                    this.RaisePropertyChanged("tarihtablosu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfSalturgalerilist", Namespace="http://tempuri.org/", ItemName="salturgalerilist")]
    [System.SerializableAttribute()]
    public class ArrayOfSalturgalerilist : System.Collections.Generic.List<izindeturizm.ServiceReference1.salturgalerilist> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="salturgalerilist", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class salturgalerilist : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalturTurResimField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SalturTurResim {
            get {
                return this.SalturTurResimField;
            }
            set {
                if ((object.ReferenceEquals(this.SalturTurResimField, value) != true)) {
                    this.SalturTurResimField = value;
                    this.RaisePropertyChanged("SalturTurResim");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.SalturWebServiceSoap")]
    public interface SalturWebServiceSoap {
        
        // CODEGEN: http://tempuri.org/ ad alanındaki kategori öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEnYakinTarihliTurlar", ReplyAction="*")]
        izindeturizm.ServiceReference1.GetEnYakinTarihliTurlarResponse GetEnYakinTarihliTurlar(izindeturizm.ServiceReference1.GetEnYakinTarihliTurlarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEnYakinTarihliTurlar", ReplyAction="*")]
        System.Threading.Tasks.Task<izindeturizm.ServiceReference1.GetEnYakinTarihliTurlarResponse> GetEnYakinTarihliTurlarAsync(izindeturizm.ServiceReference1.GetEnYakinTarihliTurlarRequest request);
        
        // CODEGEN: http://tempuri.org/ ad alanındaki ApiKey öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTurDetayi", ReplyAction="*")]
        izindeturizm.ServiceReference1.GetTurDetayiResponse GetTurDetayi(izindeturizm.ServiceReference1.GetTurDetayiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTurDetayi", ReplyAction="*")]
        System.Threading.Tasks.Task<izindeturizm.ServiceReference1.GetTurDetayiResponse> GetTurDetayiAsync(izindeturizm.ServiceReference1.GetTurDetayiRequest request);
        
        // CODEGEN: http://tempuri.org/ ad alanındaki ApiKey öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTurResimleri", ReplyAction="*")]
        izindeturizm.ServiceReference1.GetTurResimleriResponse GetTurResimleri(izindeturizm.ServiceReference1.GetTurResimleriRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTurResimleri", ReplyAction="*")]
        System.Threading.Tasks.Task<izindeturizm.ServiceReference1.GetTurResimleriResponse> GetTurResimleriAsync(izindeturizm.ServiceReference1.GetTurResimleriRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEnYakinTarihliTurlarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEnYakinTarihliTurlar", Namespace="http://tempuri.org/", Order=0)]
        public izindeturizm.ServiceReference1.GetEnYakinTarihliTurlarRequestBody Body;
        
        public GetEnYakinTarihliTurlarRequest() {
        }
        
        public GetEnYakinTarihliTurlarRequest(izindeturizm.ServiceReference1.GetEnYakinTarihliTurlarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEnYakinTarihliTurlarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string kategori;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ApiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Password;
        
        public GetEnYakinTarihliTurlarRequestBody() {
        }
        
        public GetEnYakinTarihliTurlarRequestBody(string kategori, string ApiKey, string Password) {
            this.kategori = kategori;
            this.ApiKey = ApiKey;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEnYakinTarihliTurlarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEnYakinTarihliTurlarResponse", Namespace="http://tempuri.org/", Order=0)]
        public izindeturizm.ServiceReference1.GetEnYakinTarihliTurlarResponseBody Body;
        
        public GetEnYakinTarihliTurlarResponse() {
        }
        
        public GetEnYakinTarihliTurlarResponse(izindeturizm.ServiceReference1.GetEnYakinTarihliTurlarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEnYakinTarihliTurlarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public izindeturizm.ServiceReference1.ArrayOfSalturturlistesi GetEnYakinTarihliTurlarResult;
        
        public GetEnYakinTarihliTurlarResponseBody() {
        }
        
        public GetEnYakinTarihliTurlarResponseBody(izindeturizm.ServiceReference1.ArrayOfSalturturlistesi GetEnYakinTarihliTurlarResult) {
            this.GetEnYakinTarihliTurlarResult = GetEnYakinTarihliTurlarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTurDetayiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTurDetayi", Namespace="http://tempuri.org/", Order=0)]
        public izindeturizm.ServiceReference1.GetTurDetayiRequestBody Body;
        
        public GetTurDetayiRequest() {
        }
        
        public GetTurDetayiRequest(izindeturizm.ServiceReference1.GetTurDetayiRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTurDetayiRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int turid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ApiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Password;
        
        public GetTurDetayiRequestBody() {
        }
        
        public GetTurDetayiRequestBody(int turid, string ApiKey, string Password) {
            this.turid = turid;
            this.ApiKey = ApiKey;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTurDetayiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTurDetayiResponse", Namespace="http://tempuri.org/", Order=0)]
        public izindeturizm.ServiceReference1.GetTurDetayiResponseBody Body;
        
        public GetTurDetayiResponse() {
        }
        
        public GetTurDetayiResponse(izindeturizm.ServiceReference1.GetTurDetayiResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTurDetayiResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public izindeturizm.ServiceReference1.ArrayOfSalturturlistesi GetTurDetayiResult;
        
        public GetTurDetayiResponseBody() {
        }
        
        public GetTurDetayiResponseBody(izindeturizm.ServiceReference1.ArrayOfSalturturlistesi GetTurDetayiResult) {
            this.GetTurDetayiResult = GetTurDetayiResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTurResimleriRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTurResimleri", Namespace="http://tempuri.org/", Order=0)]
        public izindeturizm.ServiceReference1.GetTurResimleriRequestBody Body;
        
        public GetTurResimleriRequest() {
        }
        
        public GetTurResimleriRequest(izindeturizm.ServiceReference1.GetTurResimleriRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTurResimleriRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int turid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ApiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Password;
        
        public GetTurResimleriRequestBody() {
        }
        
        public GetTurResimleriRequestBody(int turid, string ApiKey, string Password) {
            this.turid = turid;
            this.ApiKey = ApiKey;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTurResimleriResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTurResimleriResponse", Namespace="http://tempuri.org/", Order=0)]
        public izindeturizm.ServiceReference1.GetTurResimleriResponseBody Body;
        
        public GetTurResimleriResponse() {
        }
        
        public GetTurResimleriResponse(izindeturizm.ServiceReference1.GetTurResimleriResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTurResimleriResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public izindeturizm.ServiceReference1.ArrayOfSalturgalerilist GetTurResimleriResult;
        
        public GetTurResimleriResponseBody() {
        }
        
        public GetTurResimleriResponseBody(izindeturizm.ServiceReference1.ArrayOfSalturgalerilist GetTurResimleriResult) {
            this.GetTurResimleriResult = GetTurResimleriResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SalturWebServiceSoapChannel : izindeturizm.ServiceReference1.SalturWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SalturWebServiceSoapClient : System.ServiceModel.ClientBase<izindeturizm.ServiceReference1.SalturWebServiceSoap>, izindeturizm.ServiceReference1.SalturWebServiceSoap {
        
        public SalturWebServiceSoapClient() {
        }
        
        public SalturWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SalturWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalturWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalturWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        izindeturizm.ServiceReference1.GetEnYakinTarihliTurlarResponse izindeturizm.ServiceReference1.SalturWebServiceSoap.GetEnYakinTarihliTurlar(izindeturizm.ServiceReference1.GetEnYakinTarihliTurlarRequest request) {
            return base.Channel.GetEnYakinTarihliTurlar(request);
        }
        
        public izindeturizm.ServiceReference1.ArrayOfSalturturlistesi GetEnYakinTarihliTurlar(string kategori, string ApiKey, string Password) {
            izindeturizm.ServiceReference1.GetEnYakinTarihliTurlarRequest inValue = new izindeturizm.ServiceReference1.GetEnYakinTarihliTurlarRequest();
            inValue.Body = new izindeturizm.ServiceReference1.GetEnYakinTarihliTurlarRequestBody();
            inValue.Body.kategori = kategori;
            inValue.Body.ApiKey = ApiKey;
            inValue.Body.Password = Password;
            izindeturizm.ServiceReference1.GetEnYakinTarihliTurlarResponse retVal = ((izindeturizm.ServiceReference1.SalturWebServiceSoap)(this)).GetEnYakinTarihliTurlar(inValue);
            return retVal.Body.GetEnYakinTarihliTurlarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<izindeturizm.ServiceReference1.GetEnYakinTarihliTurlarResponse> izindeturizm.ServiceReference1.SalturWebServiceSoap.GetEnYakinTarihliTurlarAsync(izindeturizm.ServiceReference1.GetEnYakinTarihliTurlarRequest request) {
            return base.Channel.GetEnYakinTarihliTurlarAsync(request);
        }
        
        public System.Threading.Tasks.Task<izindeturizm.ServiceReference1.GetEnYakinTarihliTurlarResponse> GetEnYakinTarihliTurlarAsync(string kategori, string ApiKey, string Password) {
            izindeturizm.ServiceReference1.GetEnYakinTarihliTurlarRequest inValue = new izindeturizm.ServiceReference1.GetEnYakinTarihliTurlarRequest();
            inValue.Body = new izindeturizm.ServiceReference1.GetEnYakinTarihliTurlarRequestBody();
            inValue.Body.kategori = kategori;
            inValue.Body.ApiKey = ApiKey;
            inValue.Body.Password = Password;
            return ((izindeturizm.ServiceReference1.SalturWebServiceSoap)(this)).GetEnYakinTarihliTurlarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        izindeturizm.ServiceReference1.GetTurDetayiResponse izindeturizm.ServiceReference1.SalturWebServiceSoap.GetTurDetayi(izindeturizm.ServiceReference1.GetTurDetayiRequest request) {
            return base.Channel.GetTurDetayi(request);
        }
        
        public izindeturizm.ServiceReference1.ArrayOfSalturturlistesi GetTurDetayi(int turid, string ApiKey, string Password) {
            izindeturizm.ServiceReference1.GetTurDetayiRequest inValue = new izindeturizm.ServiceReference1.GetTurDetayiRequest();
            inValue.Body = new izindeturizm.ServiceReference1.GetTurDetayiRequestBody();
            inValue.Body.turid = turid;
            inValue.Body.ApiKey = ApiKey;
            inValue.Body.Password = Password;
            izindeturizm.ServiceReference1.GetTurDetayiResponse retVal = ((izindeturizm.ServiceReference1.SalturWebServiceSoap)(this)).GetTurDetayi(inValue);
            return retVal.Body.GetTurDetayiResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<izindeturizm.ServiceReference1.GetTurDetayiResponse> izindeturizm.ServiceReference1.SalturWebServiceSoap.GetTurDetayiAsync(izindeturizm.ServiceReference1.GetTurDetayiRequest request) {
            return base.Channel.GetTurDetayiAsync(request);
        }
        
        public System.Threading.Tasks.Task<izindeturizm.ServiceReference1.GetTurDetayiResponse> GetTurDetayiAsync(int turid, string ApiKey, string Password) {
            izindeturizm.ServiceReference1.GetTurDetayiRequest inValue = new izindeturizm.ServiceReference1.GetTurDetayiRequest();
            inValue.Body = new izindeturizm.ServiceReference1.GetTurDetayiRequestBody();
            inValue.Body.turid = turid;
            inValue.Body.ApiKey = ApiKey;
            inValue.Body.Password = Password;
            return ((izindeturizm.ServiceReference1.SalturWebServiceSoap)(this)).GetTurDetayiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        izindeturizm.ServiceReference1.GetTurResimleriResponse izindeturizm.ServiceReference1.SalturWebServiceSoap.GetTurResimleri(izindeturizm.ServiceReference1.GetTurResimleriRequest request) {
            return base.Channel.GetTurResimleri(request);
        }
        
        public izindeturizm.ServiceReference1.ArrayOfSalturgalerilist GetTurResimleri(int turid, string ApiKey, string Password) {
            izindeturizm.ServiceReference1.GetTurResimleriRequest inValue = new izindeturizm.ServiceReference1.GetTurResimleriRequest();
            inValue.Body = new izindeturizm.ServiceReference1.GetTurResimleriRequestBody();
            inValue.Body.turid = turid;
            inValue.Body.ApiKey = ApiKey;
            inValue.Body.Password = Password;
            izindeturizm.ServiceReference1.GetTurResimleriResponse retVal = ((izindeturizm.ServiceReference1.SalturWebServiceSoap)(this)).GetTurResimleri(inValue);
            return retVal.Body.GetTurResimleriResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<izindeturizm.ServiceReference1.GetTurResimleriResponse> izindeturizm.ServiceReference1.SalturWebServiceSoap.GetTurResimleriAsync(izindeturizm.ServiceReference1.GetTurResimleriRequest request) {
            return base.Channel.GetTurResimleriAsync(request);
        }
        
        public System.Threading.Tasks.Task<izindeturizm.ServiceReference1.GetTurResimleriResponse> GetTurResimleriAsync(int turid, string ApiKey, string Password) {
            izindeturizm.ServiceReference1.GetTurResimleriRequest inValue = new izindeturizm.ServiceReference1.GetTurResimleriRequest();
            inValue.Body = new izindeturizm.ServiceReference1.GetTurResimleriRequestBody();
            inValue.Body.turid = turid;
            inValue.Body.ApiKey = ApiKey;
            inValue.Body.Password = Password;
            return ((izindeturizm.ServiceReference1.SalturWebServiceSoap)(this)).GetTurResimleriAsync(inValue);
        }
    }
}
